# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-textract
dependencies:
  - python=3.7 # problems with py39
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - opencv
  - poppler
  - pip:
    - streamlit
    - gradio
    - boto3
    - awscli
    - sagemaker
    - amazon-textract-helper
    - amazon-textract-geofinder
    - amazon-textract-caller
    - amazon-textract-response-parser
    - transformers
    - pandas
    - parse
    - tensorflow==2.5.0
    - torch
    - torchvision
    - scipy
    - streamlit_image_comparison
    - thop
    - einops
    - timm
    - tabulate
    - pdf2image